/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <BLE_gatt.h>
#include <BLE.h>
#include <BLE_HAL_PVT.h>
#include <BLE_STACK_PVT.h>
#include <BLE_StackGap.h>
#include <BLE_StackGatt.h>
#include <BLE_StackGattDb.h>
#include <BLE_StackHostMain.h>
#include <BLE_StackL2cap.h>
#include <BLE_StackGattServer.h>
#include <BLE_StackGattClient.h>
#include <BLE_Stack.h>
#include <BLE_eventHandler.h>
#include <BLE_custom.h>
#include <Status_LED.h>
#include <Status_LED_aliases.h>
#include <User_Button.h>
#include <User_Button_aliases.h>
#include <isr_button.h>
#include <I2C_1.h>
#include <I2C_1_I2C.h>
#include <I2C_1_PINS.h>
#include <I2C_1_I2C_PVT.h>
#include <I2C_1_PVT.h>
#include <I2C_1_BOOT.h>
#include <COZIR.h>
#include <COZIR_SPI_UART.h>
#include <COZIR_PINS.h>
#include <COZIR_SPI_UART_PVT.h>
#include <COZIR_PVT.h>
#include <COZIR_BOOT.h>
#include <CounterLP2.h>
#include <CounterLP1.h>
#include <CounterSP1.h>
#include <CounterSP2.h>
#include <Pin_SP.h>
#include <Pin_SP_aliases.h>
#include <Pin_LP.h>
#include <Pin_LP_aliases.h>
#include <Clock_Counter.h>
#include <GREEN.h>
#include <GREEN_aliases.h>
#include <BLUE.h>
#include <BLUE_aliases.h>
#include <BLE_bless_isr.h>
#include <I2C_1_SCBCLK.h>
#include <I2C_1_sda.h>
#include <I2C_1_sda_aliases.h>
#include <I2C_1_scl.h>
#include <I2C_1_scl_aliases.h>
#include <I2C_1_SCB_IRQ.h>
#include <COZIR_SCBCLK.h>
#include <COZIR_tx.h>
#include <COZIR_tx_aliases.h>
#include <COZIR_rx.h>
#include <COZIR_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

